# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Calmeii's Home Page
email: hk_huang_kun@163.com
description: > # 这是测试文档
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://calmeii.com" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown